version: "3.9"
services:
  core:
    image: "ghcr.io/yummiii/hiyori:master"
    container_name: "hiyori_core"
    restart: unless-stopped
    ports:
      - "2403:3000"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=mysql://root:root@hiyori_db/Hiyori
  db:
    image: "mariadb:10.5"
    container_name: "hiyori_db"
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=Hiyori
  
volumes:
  mariadb: